### PR TITLE
Augment info in `flow_stats_by_id`

### PR DESCRIPTION
**Pull request by gretelliz**
This is to augment the information of the flows in the structure `flow_stats_by_id` in `flow_stats`. Previously only the flow_id and the statistics were exported. Now the `match fields, the `cookie` and the `priority` are added.

See and example:

Before
```
{
    "00:00:00:00:00:00:00:01": {
        "0d024b8d679624d6c87239f0cc2bb1c8": {
            "byte_count": 140,
            "duration_nsec": 880000000,
            "duration_sec": 415,
            "packet_count": 2
        },
        "5cd66b3ec5c0437b3d163f18e8491250": {
            "byte_count": 462,
            "duration_nsec": 656000000,
            "duration_sec": 5,
            "packet_count": 11
        },...
    },...
}
```
Now
```
{
    "00:00:00:00:00:00:00:01": {
        "0d024b8d679624d6c87239f0cc2bb1c8": {
            "byte_count": 140,
            "cookie": 12310228866111668291,
            "duration_nsec": 923000000,
            "duration_sec": 491,
            "match": {
                "in_port": 1
            },
            "packet_count": 2,
            "priority": 32768
        },
        "5cd66b3ec5c0437b3d163f18e8491250": {
            "byte_count": 546,
            "cookie": 12321848580485677057,
            "duration_nsec": 546000000,
            "duration_sec": 5,
            "match": {
                "dl_type": 35020,
                "dl_vlan": 3799
            },
            "packet_count": 13,
            "priority": 1000
        },...
    }, ...
}
```

### CODE REVIEW

**Review by italovalcy — APPROVED** [review]
LGTM! Thanks for adding that extra information, Gretel! It will be very useful for the Zabbix/kytos integration!

**Comment by gretelliz** [comment]
Great! @italovalcy

**Review by viniarck — COMMENTED** [review]
The change itself looks good to me. 

@gretelliz please make sure to also update the openapi spec since you're changing it.

**Comment by gretelliz** [comment]
@viniarck, openapi is now updated!

**Comment by viniarck** [comment]
> @viniarck, openapi is now updated!

Looks good. Feel free to merge it. Thanks.

**Review by viniarck — APPROVED** [review]

**Comment by gretelliz** [comment]
You're welcome.

**Pull request merged**
