### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by gretelliz**
README.rst has been updated. 

@viniarck, let me know if it is enough.

### CODE REVIEW

**Review by viniarck — COMMENTED** [review]
@gretelliz thanks for helping out with this and updating the README.rst. 

Yes, that's what we needed, however, some links are broken, for instance, build status, coverage and quality, looks like they're pointing out to the old amlight org it should be coming from kytos-ng if you could fix it that'd be great.

**Comment by gretelliz** [comment]
Thank You! @viniarck Done

**Comment by viniarck** [comment]
> Thank You! @viniarck Done

LGTM. This repo will be linked in the upcoming release notes, great to have the badges. Thanks.

**Pull request merged**
